# Generated by Django 6.0.4 on 2026-04-20 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Kategori Adı')),
            ],
            options={
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Ürün/Hizmet Adı')),
                ('teknik', models.CharField(choices=[('emprime', 'Emprime Baskı (Su Bazlı, Plastik, Varak)'), ('nakis', 'Nakış (Aplike / Punch)'), ('dijital', 'Dijital Baskı / DTF'), ('3d', '3D Tasarım & Modelleme')], default='emprime', max_length=50, verbose_name='Üretim Tekniği')),
                ('aciklama', models.TextField(verbose_name='Teknik Açıklama ve SEO İçeriği')),
                ('kapasite_bilgisi', models.CharField(blank=True, help_text='Örn: Günlük 1000 adet basılabilir', max_length=100, null=True, verbose_name='Üretim Kapasitesi')),
                ('kumas_uygunlugu', models.CharField(blank=True, help_text='Örn: Süprem, İki İplik, Denim', max_length=100, null=True, verbose_name='Kumaş Uygunluğu')),
                ('fiyat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tahmini Fiyat (TL)')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='urunler/genel/', verbose_name='Genel Görünüm')),
                ('resim_detay', models.ImageField(blank=True, null=True, upload_to='urunler/detay/', verbose_name='Makro Çekim (Baskı/İplik Dokusu)')),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('slug', models.SlugField(blank=True, help_text='SEO dostu URL adresi. Otomatik oluşur, dokunmayın.', null=True, unique=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katalog.kategori', verbose_name='Kategorisi')),
            ],
            options={
                'verbose_name_plural': 'Ürünler',
            },
        ),
    ]
