# Generated by Django 6.0.4 on 2026-04-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teklif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100, verbose_name='Müşteri Adı')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta Adresi')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon')),
                ('urun_turu', models.CharField(max_length=100, verbose_name='Ürün Türü (Tişört, Kapüşonlu vb.)')),
                ('adet', models.PositiveIntegerField(verbose_name='Talep Edilen Adet')),
                ('tasarim', models.FileField(upload_to='teklifler/tasarimlar/', verbose_name='Tasarım Dosyası (AI, PDF, PNG)')),
                ('notlar', models.TextField(blank=True, null=True, verbose_name='Ek Notlar')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Gelen Teklifler',
            },
        ),
    ]
