# Generated by Django 6.0.4 on 2026-04-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_teklif'),
    ]

    operations = [
        migrations.CreateModel(
            name='KurumsalSayfa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Sayfa Başlığı')),
                ('icerik', models.TextField(verbose_name='Sayfa İçeriği')),
                ('sira', models.PositiveIntegerField(default=1, verbose_name='Menü Sıralaması')),
                ('slug', models.SlugField(blank=True, help_text='Otomatik oluşur.', null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Kurumsal Sayfalar',
                'ordering': ['sira'],
            },
        ),
    ]
