# Generated by Django 6.0.4 on 2026-04-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0003_kurumsalsayfa'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaskiTuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Baskı Türü Adı')),
                ('resim', models.ImageField(upload_to='baski_turleri_resimleri/')),
            ],
        ),
    ]
