# Generated by Django 6.0.4 on 2026-04-25 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0004_baskituru'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaskiTuru',
        ),
        migrations.DeleteModel(
            name='Teklif',
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='kurumsalsayfa',
            options={'verbose_name': 'Kurumsal Sayfa', 'verbose_name_plural': 'Kurumsal Sayfalar'},
        ),
        migrations.AlterModelOptions(
            name='urun',
            options={'ordering': ['-eklenme_tarihi'], 'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.RenameField(
            model_name='kategori',
            old_name='isim',
            new_name='baslik',
        ),
        migrations.RemoveField(
            model_name='kurumsalsayfa',
            name='sira',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='aciklama',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='fiyat',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='kapasite_bilgisi',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='kumas_uygunlugu',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='resim_detay',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='slug',
        ),
        migrations.AddField(
            model_name='kurumsalsayfa',
            name='aktif',
            field=models.BooleanField(default=True, verbose_name='Yayında mı?'),
        ),
        migrations.AlterField(
            model_name='kurumsalsayfa',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL Uzantısı'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='baslik',
            field=models.CharField(max_length=200, verbose_name='Ürün Adı'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='eklenme_tarihi',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='urun',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urunler', to='katalog.kategori', verbose_name='Kategorisi'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='resim',
            field=models.ImageField(upload_to='urunler/', verbose_name='Ürün Görseli'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='teknik',
            field=models.CharField(choices=[('emprime', 'Emprime Baskı'), ('nakis', 'Nakış / Bordür'), ('dijital', 'Dijital Baskı'), ('3d_nakis', '3D Kabartma Nakış')], max_length=50, verbose_name='Uygulanan Teknik'),
        ),
    ]
