# Generated by Django 6.0.4 on 2026-04-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0005_delete_baskituru_delete_teklif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teklif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('urun_turu', models.CharField(max_length=100)),
                ('adet', models.IntegerField()),
                ('notlar', models.TextField(blank=True, null=True)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
